name = "bridge"
author = "Matthew Novitt"
file = "api.toml"
script = "server_ctl.sh"
"python dependencies" = [ "gunicorn", "flask" ]

[gunicorn]
host = "localhost"
port = 8002
workers = 1

[api.auth]
filename = "auth.py"
base_url = "auth"

[api.auth.endpoints]
register = { path = "register", methods = [ "GET", "POST" ] }
login = { path = "login", methods = [ "GET", "POST" ] }
logout = { path = "logout", methods = [ "GET" ] }