name = "bridge"
author = "Matthew Novitt"
file = "api.toml" # must be the same name as the file containing this!
script = "server_ctl"
"python dependencies" = [ "waitress", "gunicorn", "flask" ]

[wsgi]
host = "localhost"
port = 8002
workers = 1

[api.auth]
filename = "auth.py"
base_url = "auth"

[api.auth.endpoints]
register = { path = "register", methods = [ "GET", "POST" ] }
login = { path = "login", methods = [ "GET", "POST" ] }
logout = { path = "logout", methods = [ "GET" ] }