name = "api"
author = "Matthew Novitt"

[docker]
image = "python:alpine3.16"
workdir = "/app"

[python]
dependencies = [ "gunicorn", "flask" ]

[wsgi]
host = "localhost"
port = 3005
workers = 1

[api.auth]
filename = "auth.py"
base_url = "auth"

[api.auth.endpoints]
register = { path = "register", methods = [ "GET", "POST" ] }
login = { path = "login", methods = [ "GET", "POST" ] }
logout = { path = "logout", methods = [ "GET" ] }